---
version: 1

kind: experiment

framework: pytorch

tags: [weightDecay0.0, Resize, 250epc, L1, 384x384, Dongyang_dataset, version_2, batch_8, base_mask, val, model_1, 5perc] 

  image: pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime
  build_steps:
    - pip install -r requirements.txt
  env_vars:
    - ['TORCH_HOME', "/data1/brainlab_project/vessel/inpainting/"]

environment:
  resources:
    cpu:
      requests: 8
      limits: 12
    memory:
      requests: 32000
      limits: 64000
    gpu:
      requests: 1
      limits: 1

declarations:
  saving_name: "test_name"              
  checkpoint_interval: 10               
  finetune_path_encoder:  "" 
  finetune_path_decoder:  "" 
  finetune_path_autoencoder: "" 
  finetune_path_bottleneck:  "" 
  finetune_path: ""
  save_path: ""
  sample_path: ""
  log_path: ""
  epochs: 250
  batch_size: 8
  lr_g: 0.0002
  lr_decrease_epoch: 25
  lr_decrease_factor: 0.5
  num_workers: 0
  checkpoint_image: 10
  latent_channels: 64
  latent_multi: 4 
  baseroot: "/brainlab_project/vessel/inpainting/Dongyang_dataset/version_2/train/without/"
  baseroot_pair: "/brainlab_project/vessel/inpainting/Dongyang_dataset/version_2/train/with/"
  test_base: "/brainlab_project/vessel/inpainting/Dongyang_dataset/version_2/test/without/"
  test_base_pair: "/brainlab_project/vessel/inpainting/Dongyang_dataset/version_2/test/with/"
  imgsize: 384
  mask_type: "free_form"  
  margin: 10
  mask_num: 14 # case5 14
  bbox_shape: 30
  max_angle: 10
  max_len: 50
  max_width: 15
  contrast: 1
  model: 1
  loss_function: "L1"
  gan_loss_function: "L2"
  log_interval: 5
  weight_decay:  0.001


run:
  cmd: python -u train_basic_autoencoder.py  --saving_name={{ saving_name }} \
                         --checkpoint_interval={{ checkpoint_interval }} \
                         --finetune_path_encoder={{ finetune_path_encoder }} \
                         --finetune_path_decoder={{ finetune_path_decoder }} \
                         --finetune_path_autoencoder={{ finetune_path_autoencoder }} \
                         --finetune_path_bottleneck={{ finetune_path_bottleneck }} \
                         --finetune_path={{ finetune_path }} \
                         --save_path={{ save_path }} \
                         --sample_path={{ sample_path }} \
                         --log_path={{ log_path }} \
                         --epochs={{ epochs }} \
                         --batch_size={{ batch_size }} \
                         --lr_g={{ lr_g }} \
                         --lr_decrease_epoch={{ lr_decrease_epoch }} \
                         --lr_decrease_factor={{ lr_decrease_factor }} \
                         --num_workers={{ num_workers }} \
                         --checkpoint_image={{ checkpoint_image }} \
                         --latent_channels={{ latent_channels }} \
                         --latent_multi={{ latent_multi }} \
                         --baseroot={{ baseroot }} \
                         --baseroot_pair={{ baseroot_pair }} \
                         --imgsize={{ imgsize }} \
                         --mask_type={{ mask_type }} \
                         --margin={{ margin }} \
                         --mask_num={{ mask_num }} \
                         --bbox_shape={{ bbox_shape }} \
                         --max_angle={{ max_angle }} \
                         --max_len={{ max_len }} \
                         --max_width={{ max_width }} \
                         --contrast={{ contrast }} \
                         --model={{ model }} \
                         --loss_function={{ loss_function }} \
                         --gan_loss_function={{ gan_loss_function }} \
                         --log_interval={{ log_interval }} \
                         --weight_decay={{ weight_decay }} \
                         --test_base={{ test_base }} \
                         --test_base_pair={{ test_base_pair }}
